# Generated by Django 3.1.4 on 2021-01-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newquiz',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
