# Generated by Django 3.1.4 on 2021-01-31 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_newquiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newquiz',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 1, 31, 10, 3, 4, 321979, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuizAttempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('correct', models.IntegerField(blank=True, default=None, null=True)),
                ('incorrect', models.IntegerField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
